Extension { #name : 'BlElement' }

{ #category : '*MetaStash-Model-Bloc' }
BlElement >> metaStashBackground [

	<MetaStash: #Bloc>
	^ MetaStashDescriptionAccessor accessor: #background
]

{ #category : '*MetaStash-Model-Bloc' }
BlElement >> metaStashBorder [

	<MetaStash: #Bloc>
	^ MetaStashDescriptionAccessor accessor: #border
]

{ #category : '*MetaStash-Model-Bloc' }
BlElement >> metaStashChildren [

	<MetaStash: #Bloc>
	^ MetaStashDescriptionAccessor accessor: #children
]

{ #category : '*MetaStash-Model-Bloc' }
BlElement >> metaStashClipChildren [

	<MetaStash: #Bloc>
	^ MetaStashDescriptionAccessor accessor: #clipChildren
]

{ #category : '*MetaStash-Model-Bloc' }
BlElement >> metaStashCompositingMode [

	<MetaStash: #Bloc>
	^ MetaStashDescriptionAccessor accessor: #compositingMode
]

{ #category : '*MetaStash-Model-Bloc' }
BlElement >> metaStashCompositionLayer [

	<MetaStash: #Bloc>
	^ MetaStashDescriptionAccessor accessor: #compositionLayer
]

{ #category : '*MetaStash-Model-Bloc' }
BlElement >> metaStashConstraints [

	<MetaStash: #Bloc>
	^ MetaStashDescriptionAccessor accessor: #constraints
]

{ #category : '*MetaStash-Model-Bloc' }
BlElement >> metaStashEffect [

	<MetaStash: #Bloc>
	^ MetaStashDescriptionAccessor accessor: #effect
]

{ #category : '*MetaStash-Model-Bloc' }
BlElement >> metaStashElevation [

	<MetaStash: #Bloc>
	^ MetaStashDescriptionAccessor accessor: #elevation
]

{ #category : '*MetaStash-Model-Bloc' }
BlElement >> metaStashExtent [

	<MetaStash: #Bloc>
	^ MetaStashDescriptionAccessor accessor: #extent
]

{ #category : '*MetaStash-Model-Bloc' }
BlElement >> metaStashFocusability [

	<MetaStash: #Bloc>
	^ MetaStashDescriptionAccessor accessor: #focusability
]

{ #category : '*MetaStash-Model-Bloc' }
BlElement >> metaStashFocused [

	<MetaStash: #Bloc>
	^ MetaStashDescriptionAccessor accessor: #focused
]

{ #category : '*MetaStash-Model-Bloc' }
BlElement >> metaStashFocusedBounds [

	<MetaStash: #Bloc>
	^ MetaStashDescriptionAccessor accessor: #focusedBounds
]

{ #category : '*MetaStash-Model-Bloc' }
BlElement >> metaStashGeometry [

	<MetaStash: #Bloc>
	^ MetaStashDescriptionAccessor accessor: #geometry
]

{ #category : '*MetaStash-Model-Bloc' }
BlElement >> metaStashGeometryBounds [

	<MetaStash: #Bloc>
	^ MetaStashDescriptionAccessor accessor: #geometryBounds
]

{ #category : '*MetaStash-Model-Bloc' }
BlElement >> metaStashHeight [

	<MetaStash: #Bloc>
	^ MetaStashDescriptionAccessor accessor: #height
]

{ #category : '*MetaStash-Model-Bloc' }
BlElement >> metaStashId [

	<MetaStash: #Bloc>
	^ MetaStashDescriptionAccessor accessor: #id
]

{ #category : '*MetaStash-Model-Bloc' }
BlElement >> metaStashInvalidationBounds [

	<MetaStash: #Bloc>
	^ MetaStashDescriptionAccessor accessor: #invalidationBounds
]

{ #category : '*MetaStash-Model-Bloc' }
BlElement >> metaStashLayout [

	<MetaStash: #Bloc>
	^ MetaStashDescriptionAccessor accessor: #layout
]

{ #category : '*MetaStash-Model-Bloc' }
BlElement >> metaStashLocalTheme [

	<MetaStash: #Bloc>
	^ MetaStashDescriptionAccessor accessor: #localTheme
]

{ #category : '*MetaStash-Model-Bloc' }
BlElement >> metaStashMargin [

	<MetaStash: #Bloc>
	^ MetaStashDescriptionAccessor accessor: #margin
]

{ #category : '*MetaStash-Model-Bloc' }
BlElement >> metaStashMaxHeight [

	<MetaStash: #Bloc>
	^ MetaStashDescriptionAccessor accessor: #maxHeight
]

{ #category : '*MetaStash-Model-Bloc' }
BlElement >> metaStashMaxSize [

	<MetaStash: #Bloc>
	^ MetaStashDescriptionAccessor accessor: #maxSize
]

{ #category : '*MetaStash-Model-Bloc' }
BlElement >> metaStashMaxWidth [

	<MetaStash: #Bloc>
	^ MetaStashDescriptionAccessor accessor: #maxWidth
]

{ #category : '*MetaStash-Model-Bloc' }
BlElement >> metaStashMeasuredExtent [

	<MetaStash: #Bloc>
	^ MetaStashDescriptionAccessor accessor: #measuredExtent
]

{ #category : '*MetaStash-Model-Bloc' }
BlElement >> metaStashMinHeight [

	<MetaStash: #Bloc>
	^ MetaStashDescriptionAccessor accessor: #minHeight
]

{ #category : '*MetaStash-Model-Bloc' }
BlElement >> metaStashMinSize [

	<MetaStash: #Bloc>
	^ MetaStashDescriptionAccessor accessor: #minSize
]

{ #category : '*MetaStash-Model-Bloc' }
BlElement >> metaStashMinWidth [

	<MetaStash: #Bloc>
	^ MetaStashDescriptionAccessor accessor: #minWidth
]

{ #category : '*MetaStash-Model-Bloc' }
BlElement >> metaStashMouseCursor [

	<MetaStash: #Bloc>
	^ MetaStashDescriptionAccessor accessor: #mouseCursor
]

{ #category : '*MetaStash-Model-Bloc' }
BlElement >> metaStashOpacity [

	<MetaStash: #Bloc>
	^ MetaStashDescriptionAccessor accessor: #opacity
]

{ #category : '*MetaStash-Model-Bloc' }
BlElement >> metaStashOutskirts [

	<MetaStash: #Bloc>
	^ MetaStashDescriptionAccessor accessor: #outskirts
]

{ #category : '*MetaStash-Model-Bloc' }
BlElement >> metaStashPadding [

	<MetaStash: #Bloc>
	^ MetaStashDescriptionAccessor accessor: #padding
]

{ #category : '*MetaStash-Model-Bloc' }
BlElement >> metaStashPosition [

	<MetaStash: #Bloc>
	^ MetaStashDescriptionAccessor accessor: #position
]

{ #category : '*MetaStash-Model-Bloc' }
BlElement >> metaStashShortcuts [

	<MetaStash: #Bloc>
	^ MetaStashDescriptionAccessor accessor: #shortcuts
]

{ #category : '*MetaStash-Model-Bloc' }
BlElement >> metaStashSize [

	<MetaStash: #Bloc>
	^ MetaStashDescriptionAccessor accessor: #size
]

{ #category : '*MetaStash-Model-Bloc' }
BlElement >> metaStashStyleSheet [

	<MetaStash: #Bloc>
	^ MetaStashDescriptionAccessor accessor: #styleSheet
]

{ #category : '*MetaStash-Model-Bloc' }
BlElement >> metaStashTransformation [

	<MetaStash: #Bloc>
	^ MetaStashDescriptionAccessor accessor: #transformation
]

{ #category : '*MetaStash-Model-Bloc' }
BlElement >> metaStashTransformedBounds [

	<MetaStash: #Bloc>
	^ MetaStashDescriptionAccessor accessor: #transformedBounds
]

{ #category : '*MetaStash-Model-Bloc' }
BlElement >> metaStashVisibility [

	<MetaStash: #Bloc>
	^ MetaStashDescriptionAccessor accessor: #visibility
]

{ #category : '*MetaStash-Model-Bloc' }
BlElement >> metaStashWidth [

	<MetaStash: #Bloc>
	^ MetaStashDescriptionAccessor accessor: #width
]
