Class {
	#name : 'MetaStashSerializationConstructor',
	#superclass : 'Object',
	#instVars : [
		'constructorString'
	],
	#category : 'MetaStash-Serialization',
	#package : 'MetaStash-Serialization'
}

{ #category : 'accessing' }
MetaStashSerializationConstructor >> constructorString [

	^ constructorString
]

{ #category : 'accessing' }
MetaStashSerializationConstructor >> constructorString: anObject [

	constructorString := anObject
]
